services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    env_file:
      - ./backend/.env
    container_name: counselai-backend
    ports:
      - "3001:3001"
    networks:
      - counselai-net
    restart: unless-stopped

  # frontend-prod:
  #   build:
  #     context: .
  #     dockerfile: frontend/Dockerfile
  #     target: runner # Use the 'runner' stage for production
  #   container_name: counselai-frontend-prod
  #   ports:
  #     - "3000:3000"
  #   networks:
  #     - counselai-net
  #   depends_on:
  #     - backend
  #   restart: unless-stopped

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      args:
        - NEXT_PUBLIC_API_URL=${NEXT_PUBLIC_API_URL}
    ports:
      - "3000:3000"
    env_file:
      - ./.env
    depends_on:
      - backend

networks:
  counselai-net:
    driver: bridge 